name: Push Docker Image

on:
  push:
    branches: [ main ]
    
jobs: 
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure docker us-east1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t us-east1-docker.pkg.dev/ai-interview-frontend/ai-interview-frontend/ai-interview-frontend:latest .
      
      - name: Push Docker Image
        run: docker push us-east1-docker.pkg.dev/ai-interview-frontend/ai-interview-frontend/ai-interview-frontend:latest
