creation_rules:
  - path_regex: .*\.enc\.yaml$
    encrypted_regex: ^(data|stringData|password|token|key|secret|env_vars)$
    gcp_kms: projects/terraform-practice-455719/locations/global/keyRings/sops-keyring/cryptoKeys/sops-key
