/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileCreateImport } from './routes/profile-create'
import { Route as LoginImport } from './routes/login'
import { Route as SignUpImport } from './routes/SignUp'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileCreateRoute = ProfileCreateImport.update({
  id: '/profile-create',
  path: '/profile-create',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRoute = SignUpImport.update({
  id: '/SignUp',
  path: '/SignUp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/SignUp': {
      id: '/SignUp'
      path: '/SignUp'
      fullPath: '/SignUp'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile-create': {
      id: '/profile-create'
      path: '/profile-create'
      fullPath: '/profile-create'
      preLoaderRoute: typeof ProfileCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '/login': typeof LoginRoute
  '/profile-create': typeof ProfileCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '/login': typeof LoginRoute
  '/profile-create': typeof ProfileCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '/login': typeof LoginRoute
  '/profile-create': typeof ProfileCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/SignUp' | '/login' | '/profile-create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/SignUp' | '/login' | '/profile-create'
  id: '__root__' | '/' | '/SignUp' | '/login' | '/profile-create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignUpRoute: typeof SignUpRoute
  LoginRoute: typeof LoginRoute
  ProfileCreateRoute: typeof ProfileCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignUpRoute: SignUpRoute,
  LoginRoute: LoginRoute,
  ProfileCreateRoute: ProfileCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/SignUp",
        "/login",
        "/profile-create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/SignUp": {
      "filePath": "SignUp.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile-create": {
      "filePath": "profile-create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
