name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
   
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
        
      - name: Build Docker image
        run: docker buildx build -f Dockerfile.prod --build-arg VITE_MODE=production -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-interview-frontend/ai-interview-frontend:latest .

      - name: Push Docker Images
        run: |
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-interview-frontend/ai-interview-frontend:latest
          docker tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-interview-frontend/ai-interview-frontend:latest us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-interview-frontend/ai-interview-frontend:${{ github.sha }}
          docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-interview-frontend/ai-interview-frontend:${{ github.sha }}
